# Generated by Django 3.1.7 on 2021-05-06 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Causes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('Medium', 'Medium'), ('High', 'High'), ('Low', 'Low')], default=(('Medium', 'Medium'), ('High', 'High'), ('Low', 'Low')), max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default=(('Pending', 'Pending'), ('Approved', 'Approved')), max_length=20)),
                ('cause_image', models.ImageField(blank=True, upload_to='causes')),
                ('ngo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(blank=True)),
                ('date_donated', models.DateTimeField(auto_now_add=True)),
                ('cause', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.causes')),
                ('donor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.customerprofile')),
            ],
        ),
    ]
