# Generated by Django 3.1.7 on 2021-05-08 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210508_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='ngoname',
            new_name='ngo_name',
        ),
    ]
