# Generated by Django 3.1.7 on 2021-05-09 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210509_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(default='auth.User', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.customerprofile'),
        ),
    ]
