# Generated by Django 3.1.7 on 2021-05-09 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210510_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(default='auth.User.id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.customerprofile'),
        ),
    ]
