# Generated by Django 3.1.7 on 2021-05-09 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20210510_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(default='auth.User', on_delete=django.db.models.deletion.CASCADE, to='account.customerprofile'),
        ),
    ]
