# Generated by Django 3.1.7 on 2021-05-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20210510_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payment_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
