# Generated by Django 3.1.7 on 2021-05-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20210510_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='causes',
            name='amount_required',
            field=models.PositiveBigIntegerField(blank=True, default=3000),
            preserve_default=False,
        ),
    ]
