# Generated by Django 3.1.7 on 2021-05-10 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_causes_amount_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causes',
            name='ngo',
            field=models.ForeignKey(default='auth.User', on_delete=django.db.models.deletion.CASCADE, to='account.userprofile'),
        ),
    ]
