# Generated by Django 3.1.7 on 2021-05-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_donation_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='updated_by',
        ),
    ]
