# Generated by Django 3.1.7 on 2021-05-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20210511_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='causes',
            name='updated_by',
        ),
    ]
