# Generated by Django 3.1.7 on 2021-05-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_remove_causes_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='profile',
            field=models.ImageField(blank=True, upload_to='donor/profile'),
        ),
    ]
